### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bradennapier** [avanes/postcss-color-alpha#14]
This is not working for me.  It is changing

```
.background {
   background-color: #121519.3;
}
```

to 

```
.background {
   background-color: #121519 0.3;
}
```

**Comment by avanes** [comment]
@bradennapier I tried your case and got `.background  { background-color: rgba(18, 21, 25, 0.3); }`
Please give me your set of plugins.

**Comment by bradennapier** [comment]
It appears that having sass loader included caused the issue.  I removed and all is fine now.  Was css file, not sure what was up!  Thanks
