### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by ai** [avanes/postcss-color-alpha#4]
Please, publish npm package by `npm publish`. I want to use your plugin on Amplifr.

**Comment by ai** [comment]
@avanes BTW, do not forget to update `ChangeLog.md` on every npm release.

**Comment by avanes** [comment]
Opensource is...
I'll do my homework =)

**Comment by ai** [comment]
:D

**Comment by avanes** [comment]
Released! Yay!
postcss-color-alpha@0.0.4
