### ISSUE TITLE
Gradient problem

### ISSUE THREAD

**Issue by ai** [avanes/postcss-color-alpha#6]
Sorry, I didn’t investigate this issue yet.

Input:

``` css
background: #004400 radial-gradient(white(0.05), white(0))
```

Output (according Chrome DevTools):

``` css
background: #004400 rgba(255, 255, 255, 0.05) white(255, 255, 255, 0)
```

Seems like plugin broke `radial-gradient` word.

/cc @avanes

**Comment by avanes** [comment]
Arghhh... Brackets hell. Can't invent regexp to spllit `#004400 radial-gradient(white(0.05), white(0))` to `[ '#004400', 'radial-gradient(white(0.05) white(0))' ]` (not to `[ '#004400', 'radial-gradient(white(0.05),', 'white(0))' ]`)

**Comment by ai** [comment]
Use `postcss.list` to split values by space.

**Comment by ai** [comment]
Docs: https://github.com/postcss/postcss/blob/master/API.md#list-module

**Comment by avanes** [comment]
Fixed
`postcss-color-alpha@0.0.5`
