### ISSUE TITLE
postcss-simple-vars

### ISSUE THREAD

**Issue by mmilo** [avanes/postcss-color-alpha#8]
Haven’t been able to get this to work with the [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) extension.

Trying to do something along the lines of `$pale-color: rgba($bright-color, .5);` but no variation of the syntax seems to product the desired output.

**Comment by avanes** [comment]
I've got something similar on my last project. I used postcss-color-function `color($var a(.5))` for such cases.
Planing refactor plugin, will look on this issues.

**Comment by avanes** [comment]
Try to place postcss-simple-vars before postcss-color-alpha in plugins array.
