### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [avanes/postcss-color-alpha#9]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by avanes** [comment]
Updated: 78d67c6

**Comment by TrySound** [comment]
Minor release, please. API was compatibly extented.

**Comment by avanes** [comment]
Updated: 03bffa3

**Comment by TrySound** [comment]
Thanks!
